services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - 0.0.0.0:5438:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgres/data

  migrations:
    build: .
    env_file: .env
    healthcheck:
      test: ["CMD", "python manage.py migrate"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - .:/code
    command: python manage.py migrate
    depends_on:
      db:
        condition: service_healthy

  apiweb:
    build: .
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    stdin_open: true
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      migrations:
        condition: service_completed_successfully
      db:
        condition: service_healthy
volumes:
  pgdata:
