# Generated by Django 4.1.7 on 2023-03-02 07:57

from django.db import migrations
import pessoas.models


class Migration(migrations.Migration):
    dependencies = [
        ("pessoas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="pessoa",
            managers=[
                ("objects", pessoas.models.CustomUserManager()),
            ],
        ),
    ]
