# Generated by Django 4.1.7 on 2023-03-02 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contas", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transacao",
            fields=[
                ("idTransacao", models.BigAutoField(primary_key=True, serialize=False)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=14)),
                ("dataTransacao", models.DateTimeField(auto_now_add=True)),
                ("tipo", models.CharField(max_length=20)),
                (
                    "idConta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacoes",
                        to="contas.conta",
                    ),
                ),
            ],
        ),
    ]
