# Generated by Django 4.1.7 on 2023-03-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conta",
            fields=[
                ("idConta", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "saldo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "limiteSaqueDiario",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("flagAtivo", models.BooleanField(default=True)),
                ("tipoConta", models.IntegerField()),
                ("dataCriacao", models.DateTimeField(auto_now_add=True)),
                ("ultimaAtualizacao", models.DateField(auto_now=True)),
            ],
        ),
    ]
