# Generated by Django 4.1.7 on 2023-03-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contas", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conta",
            name="apelido",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
